### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by NosferatuJoe** [srpg/quakesounds#1]
First of all thank you for creating this plugin in SP.
I was just wondering since I'm about to test this, does it come with a config or does it need to be manually edited in the .py?

A little more documentation on the github would be nice, but besides that I'm really thankful that you took the time to code this plugin!

**Comment by srpg** [comment]
Inside of .py file you need edit numbers value which is located bottom of the code and your welcome.
At line 92, you see there something like: _sounds = {5: 'multikill.mp3'}

**Comment by srpg** [comment]
Hi, i made a wiki about adding sounds and how to set up it download.
Go check it: [Wiki](https://github.com/srpg/quakesounds/wiki)
